task_new:
    path: /new
    defaults: {_controller: "AppBundle:Staff/Task:new"}
    methods: POST

task_edit:
    path: /edit/{id}
    defaults: {_controller: "AppBundle:Staff/Task:new", id : null}
    methods: POST

task_list:
    path: /list
    defaults: {_controller: "AppBundle:Staff/Task:tasks"}
    methods: POST

task_detail:
    path: /detail/{id}
    defaults: {_controller: "AppBundle:Staff/Task:task", id : null}
    methods: POST

task_serach:
    path: /search/{search}
    defaults: {_controller: "AppBundle:Staff/Task:search", search : null}
    methods: POST

task_remove:
    path: /remove/{id}
    defaults: {_controller: "AppBundle:Staff/Task:remove", id : null}
    methods: POST