BackendBundle\Entity\ClientExtra:
    type: entity
    table: client_extra
    indexes:
        fk_client_extra_client1_idx:
            columns:
                - client_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
