BackendBundle\Entity\Contact:
    type: entity
    table: contact
    indexes:
        fk_contact_user1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        emargencyContact:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: emargency_contact
        landPhone:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: land_phone
        address:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
    oneToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
