BackendBundle\Entity\EmployeeOrderCategory:
    type: entity
    table: employee_order_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryName:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: category_name
        pricePerHour:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: price_per_hour
    lifecycleCallbacks: {  }
