BackendBundle\Entity\Induction:
    type: entity
    table: induction
    indexes:
        fk_induction_form1_idx:
            columns:
                - form_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        form:
            targetEntity: Form
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                form_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        job:
            targetEntity: Job
            cascade: {  }
            fetch: LAZY
            mappedBy: induction
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
