BackendBundle\Entity\UserAvatar:
    type: entity
    table: user_avatar
    indexes:
        fk_employee_avatar_user1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        alt:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        width:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        height:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        path:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fileName:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: file_name
        mime:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        storageType:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: storage_type
        size:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        uploadedDate:
            type: datetime
            nullable: true
            column: uploaded_date
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
